name: multi_screen_presentation_example
description: "Demonstrates how to use the multi_screen_presentation plugin."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  multi_screen_presentation:
    path: ../
  
  device_info_plus: ^13.2.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true